// PLACEHOLDER — this file is normally auto-generated by running
// `flutterfire configure` from this project's root, which overwrites it
// completely with your real Firebase project's Web app keys. Until you've
// run that command, this throws a clear error instead of a cryptic
// Firebase SDK failure if kUseFirebase is ever flipped to true
// prematurely.
//
// See FIREBASE_SETUP.md for the full setup checklist. This must point at
// the SAME Firebase project as dating_app/lib/firebase_options.dart —
// they share one Firestore database.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'firebase_options.dart is still the placeholder. Run `flutterfire configure` '
      'from this project root (selecting the same Firebase project as dating_app, '
      'Web platform only) before setting kUseFirebase = true (see FIREBASE_SETUP.md).',
    );
  }
}
