// PLACEHOLDER — this file is normally auto-generated by running
// `flutterfire configure` from the project root, which overwrites it
// completely with your real Firebase project's keys. Until you've run
// that command, this throws a clear error instead of a cryptic Firebase
// SDK failure if kUseFirebase is ever flipped to true prematurely.
//
// See FIREBASE_SETUP.md for the full setup checklist.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'firebase_options.dart is still the placeholder. Run `flutterfire configure` '
      'from the project root to generate real Firebase config before setting '
      'kUseFirebase = true (see FIREBASE_SETUP.md).',
    );
  }
}
